プルリクエストについた指摘の修正
s55541kw/No4WADA pull request #6
Opened 2024-04-09 01:58 UTC by s55541kw

- aタグの入れ子を修正しました。
  - del.php L:28
- ボタン名の変更をしました。
  - del.php L:28
- クラス名をアンダーバー区切りに統一しました。
   - del.php L:27
- 打ち間違えていた部分に＝追加しました。
   - index.php L:12
- 不要な空白を削除しました。
   - index.php L:16
- theadとtbodyの使い方を修正しました。
   - index.php L:41,55
- インデントを修正しました。
  - style.css 全体
- UpdatedをUpdateDateに変更しました。
  - update_done.php L:10,30,36

>buttonにはデフォルトでcursor: pointerがついているかと思ったのですが、こちらは必要でしょうか？
>>cursor: pointer;を入れておくとマウスをボタンに重ねるとき指になるので入れていました。どちらかというと入れておきたいんですが消したほうがいいでしょうか？

2024-04-09 02:07 UTC, asada-no4 reviewed
取り急ぎ1点だけコメントします。

> cursor: pointer;を入れておくとマウスをボタンに重ねるとき指になるので入れていました。どちらかというと入れておきたいんですが消したほうがいいでしょうか？

デフォルトが指なのかと勘違いしてました🙇‍♀️
https://developer.mozilla.org/ja/docs/Web/HTML/Element/button
↑を見るとデフォルトはカーソルのようですね。であれば今のcursor: pointerをつけている状態で良さそうです。失礼しました。

2024-04-10 00:51 UTC, asada-no4 requested changes

2024-04-10 00:51 UTC, asada-no4 commented on web/del.php
> +        <a href="index.php"><button name="btn_not_remove">いいえ</button></a>
https://yoshikawaweb.com/element/
ここを見ると、aタグの中にbuttonタグも良くない気がするので、
aタグの中にspanタグを入れるのはどうでしょうか？
![image](https://github.com/s55541kw/No4WADA/assets/84558556/9e2d4eb1-9941-4cc2-94dd-e5b8d32c1067)

2024-04-10 00:51 UTC, asada-no4 commented on web/index.php
> +    <div class="btn-wrp">
ここもクラス名にハイフンが使われています。

2024-04-10 00:52 UTC, asada-no4 commented
他は直っていそうに思いました🙇‍♀️

2024-04-10 02:11 UTC, s55541kw commented on web/del.php
> +        <a href="index.php"><button name="btn_not_remove">いいえ</button></a>
aタグの中にspanタグを入れるように修正しました。

2024-04-10 02:24 UTC, s55541kw commented on web/index.php
> +    <div class="btn-wrp">
ファイルを見直して-がついているクラスを修正しました。
直した過程でもともと機能していなかったクラスを削除しました。

2024-04-10 02:38 UTC, s55541kw commented
テーブルデータ導入処理(index.php L:51-73)のクラスを少し変更しました。
修正点ではないので無視していただいて大丈夫です。

2024-04-10 02:57 UTC, asada-no4 requested changes

2024-04-10 02:57 UTC, asada-no4 commented on web/index.php
> +                        <div class="btn_wrp"><a href="update.php?Id=<?php echo $Row['Id']; ?>"><button id="btn_upd">編集</button></a>
ここもaタグのなかにbuttonが入っている気がします。
下の削除ボタンも同様ですね。

2024-04-10 02:57 UTC, asada-no4 commented on web/index.php
> +                        <div class="btn_wrp"><a href="update.php?Id=<?php echo $Row['Id']; ?>"><button id="btn_upd">編集</button></a>
今回の指摘とちょっとずれてしまうのですが、buttonのonclickでページ遷移している部分と、aタグのhrefでページ遷移している部分があるのが気になりました。

- button…押してイベントを発火させる時に利用（ページ遷移なし）
- a…押してページ遷移する時に利用

として使い分けができると良さそうです。

参照: https://codinghaku.com/between-button-a/

2024-04-10 03:02 UTC, asada-no4 commented on web/index.php
> +                        <div class="btn_wrp"><a href="update.php?Id=<?php echo $Row['Id']; ?>"><button id="btn_upd">編集</button></a>
> 今回の指摘とちょっとずれてしまう

これは追加指摘になるので（[Slack](https://no4-chat.slack.com/archives/C06132X7XNU/p1712709234335799)）にあるとおり、一旦修正しなくて大丈夫です🙇‍♀️

2024-04-10 04:16 UTC, s55541kw commented on web/index.php
> +                        <div class="btn_wrp"><a href="update.php?Id=<?php echo $Row['Id']; ?>"><button id="btn_upd">編集</button></a>
すみません見落としてました🙇‍♀️
spanタグに修正したのでご確認お願いします。

2024-04-10 04:22 UTC, asada-no4 approved these changes
指摘箇所が修正されていることを確認しました
![image](https://github.com/s55541kw/No4WADA/assets/84558556/1deb4960-fc9f-40bf-b549-ceb77b8de559)

2024-04-10 04:36 UTC, merged